apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-java
  template:
    metadata:
      labels:
        app: demo-java
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: demo-java
          image: walterbamac/demo-devops-java:latest
          ports:
            - containerPort: 8080

          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: APP_NAME

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: PORT

            - name: NAME_DB
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: NAME_DB

            - name: USERNAME_DB
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: USERNAME_DB

            - name: PASSWORD_DB
              valueFrom:
                secretKeyRef:
                  name: demo-secret
                  key: PASSWORD_DB

          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3

          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3